/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.intelnalFrame;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import model.DAO.CapacidadeDAO;
import model.DAO.CursoDAO;
import model.DAO.EleCompetenciasDAO;
import model.DAO.ObjConhecimentoDAO;
import model.DAO.UniCompetenciasDAO;
import model.Entity.Capacidade;
import model.Entity.ObjConhecimento;

/**
 *
 * @author oem
 */
public class jTreeSaep extends javax.swing.JInternalFrame {

    /**
     * Creates new form jTreeSaep
     */
    //cria os modelos
    DefaultTreeModel dft;
    DefaultMutableTreeNode root;
    DefaultMutableTreeNode curso;
    DefaultMutableTreeNode categoriaCap;
    DefaultMutableTreeNode UniCompete;
    DefaultMutableTreeNode basico;
    DefaultMutableTreeNode tecnico;
    DefaultMutableTreeNode gestao;
    DefaultMutableTreeNode capacidade;
    DefaultListModel modelo;

    public jTreeSaep() {
        initComponents();
        //POPULA OS COMBOBOX's
        popCboxs();
        //CRIA PRIMEIRA PASTA PADRÃO JTREE
        root = new DefaultMutableTreeNode("Curso");
        //METODO QUE ADICIONA OS CURSOS E CAPACIDADES BASICA, TECNICA E GESTAO EM CADA UM
        addCurso();
        //SETA O MODELO ATE AQUI CRIADO
        dft = new DefaultTreeModel(root);
        //DA PARA A JTREE O MODELO SETADO
        treeTeste.setModel(dft);

        //EVENTO DE CLIQUE NA TREE APENAS NO NÍVEL DESEJADO
        treeTeste.getSelectionModel().addTreeSelectionListener(new TreeSelectionListener() {

            @Override
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeTeste.getLastSelectedPathComponent();
                if (selectedNode.getLevel() == 4) {
                    lblEleCompetencias.setText(selectedNode.getUserObject().toString());
                }
            }
        });

    }

    //PREENCHE COMBOBOX COM CAPACIDADES DO BANCO
    private void popCboxs() {
        EleCompetenciasDAO daoEle = new EleCompetenciasDAO();

        daoEle.findAll().forEach((ec) -> {
            cboxEleCompetencias.addItem(ec);
        });
        ObjConhecimentoDAO daoObj = new ObjConhecimentoDAO();

        daoObj.findAll().forEach((oc) -> {
            cboxObjConhecimento.addItem(oc);
        });

    }

    private void addCurso() {
        CursoDAO dao = new CursoDAO();

        dao.findAll().forEach((c) -> {

            curso = new DefaultMutableTreeNode(c.toString());
            root.add(curso);
            addUniCompete(c.getId());

            addCapacidade(c.getId());
        });
    }

    private void addUniCompete(long cursoId) {

        UniCompetenciasDAO dao = new UniCompetenciasDAO();

        dao.findAllCurso(cursoId).forEach((u) -> {

            UniCompete = new DefaultMutableTreeNode(u);

            curso.add(UniCompete);

            basico = new DefaultMutableTreeNode("Básico");
            UniCompete.add(basico);
            tecnico = new DefaultMutableTreeNode("Técnico");
            UniCompete.add(tecnico);
            gestao = new DefaultMutableTreeNode("Gestão");
            UniCompete.add(gestao);

        });

    }

    private void addCapacidade(long cursoId) {

        CapacidadeDAO dao = new CapacidadeDAO();

        dao.findAllCurso(cursoId).forEach((ca) -> {

            switch (ca.getTipo()) {
                case 0:
                    categoriaCap = new DefaultMutableTreeNode(ca);
                    basico.add(categoriaCap);
                    break;
                case 1:
                    categoriaCap = new DefaultMutableTreeNode(ca);
                    tecnico.add(categoriaCap);
                    break;
                case 2:
                    categoriaCap = new DefaultMutableTreeNode(ca);
                    gestao.add(categoriaCap);
                    break;
                default:
                    break;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTeste = new javax.swing.JTree();
        lblEleCompetencias = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cboxEleCompetencias = new javax.swing.JComboBox<>();
        lblEleCompetencias1 = new javax.swing.JLabel();
        cboxObjConhecimento = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listObjCon = new javax.swing.JList<>();
        lblDesc = new javax.swing.JLabel();
        btnAddObjCon = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeTeste.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeTeste);

        lblEleCompetencias.setText("Elemento de competência");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblEleCompetencias1.setText("Objeto de conhecimento");

        jScrollPane2.setViewportView(listObjCon);

        lblDesc.setText("Descrição");

        btnAddObjCon.setText("Adicionar");
        btnAddObjCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddObjConMouseClicked(evt);
            }
        });

        btnSalvar.setText("Salvar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnRemover.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxObjConhecimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxEleCompetencias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEleCompetencias)
                                    .addComponent(lblEleCompetencias1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddObjCon, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEleCompetencias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxEleCompetencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEleCompetencias1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxObjConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddObjCon)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(12, 12, 12)
                                .addComponent(btnRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDesc))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddObjConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddObjConMouseClicked

        modelo = new DefaultListModel();

        ObjConhecimento objc = new ObjConhecimento();

        objc = (ObjConhecimento) cboxObjConhecimento.getSelectedItem();

        for (int i = 0; i < listObjCon.getModel().getSize(); i++) {
            modelo.addElement(listObjCon.getModel().getElementAt(i));
        }
        if (modelo.contains(objc)) {
            JOptionPane.showMessageDialog(null, "Já adicionado!");
        } else {

            modelo.addElement(objc);
            listObjCon.setModel(modelo);
        }
    }//GEN-LAST:event_btnAddObjConMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObjCon;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cboxEleCompetencias;
    private javax.swing.JComboBox<Object> cboxObjConhecimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEleCompetencias;
    private javax.swing.JLabel lblEleCompetencias1;
    private javax.swing.JList<String> listObjCon;
    private javax.swing.JTree treeTeste;
    // End of variables declaration//GEN-END:variables
}
